class Download < ApplicationRecord
  belongs_to :request
  belongs_to :download_client, optional: true
  has_many :request_events, dependent: :nullify

  SHOW_PAGE_BROADCAST_ATTRIBUTES = %w[name progress size_bytes status].freeze

  enum :status, {
    queued: 0,
    downloading: 1,
    paused: 2,
    completed: 3,
    failed: 4
  }

  validates :status, presence: true
  after_create_commit :broadcast_request_show_refresh_later
  after_update_commit :broadcast_request_show_refresh_later_if_needed
  after_destroy_commit :broadcast_request_show_refresh_later

  scope :active, -> { where(status: [:queued, :downloading]) }

  def active?
    queued? || downloading?
  end

  def progress_percentage
    "#{progress}%"
  end

  # Note: completed? is auto-generated by Rails enum, no need to define it

  private

  def broadcast_request_show_refresh_later_if_needed
    broadcast_request_show_refresh_later if (previous_changes.keys & SHOW_PAGE_BROADCAST_ATTRIBUTES).any?
  end

  def broadcast_request_show_refresh_later
    Request.find_by(id: request_id)&.broadcast_show_refresh_later
  end
end
